services:
  gopher-drive:
    build:
      context: .
      dockerfile: ./cmd/gopher-drive/Dockerfile
    container_name: gopher-drive
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=gopher-drive-postgres
      - REDIS_ADDRESS=gopher-drive-redis:6379
      - MINIO_ADDRESS=http://gopher-drive-minio:9000
    ports:
      - "8080:8080"
    depends_on:
      gopher-drive-postgres:
        condition: service_healthy
      gopher-drive-migrator:
        condition: service_completed_successfully

  gopher-drive-postgres:
    image: postgres:18-alpine
    container_name: gopher-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gopher-drive-redis:
    image: redis:8-alpine
    container_name: gopher-redis
    ports:
      - "6379:6379"

  gopher-drive-minio:
    image: quay.io/minio/minio
    container_name: gopher-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data

  gopher-drive-migrator:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gopher-drive-postgres:5432/${POSTGRES_DATABASE}?sslmode=disable
      - up
    depends_on:
      gopher-drive-postgres:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data: